### ISSUE TITLE
Blank website front page

### ISSUE THREAD

**Issue by Siphiwo** [Collivery/Collivery-Virtuemart#2]
Hi, after  installing the plugin into my website, the front page when blank. Nothing is showing. I am currently using Joomla 3.6 and Vertuemart 3.0.16

**Comment by brycelarge** [comment]
this plugin only works on Joomla version 3.0.0 and Virtumart version 3.0.9, this project was last updated in Jul 2015

**Comment by Siphiwo** [comment]
Thank you for your response #brycelarge. Will I need a php developer to update the plugin so that it can work with the current Joomla & Vertuemart versions?

**Comment by brycelarge** [comment]
Yes

**Comment by Siphiwo** [comment]
Thank you for your response. One last thing, can it be expected that any of the contributors will be doing the update within this year

**Comment by brycelarge** [comment]
Not sure, however anyone can contribute
